// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

var buttonStyles = {
  backgroundColor: "white",
  border: "1px solid #48a9dc",
  color: "#48a9dc",
  cursor: "pointer",
  fontSize: "16px",
  fontWeight: "bold",
  margin: "10px 10px 0 0",
  outline: "none",
  padding: "10px",
  width: "120px",
  borderRadius: "4px"
};

function ButtonsSection(Props) {
  var handleIncrement = Props.handleIncrement;
  var handleDecrement = Props.handleDecrement;
  var handleReset = Props.handleReset;
  return React.createElement("div", undefined, React.createElement("button", {
                  style: buttonStyles,
                  onClick: handleIncrement
                }, "+"), React.createElement("button", {
                  style: buttonStyles,
                  onClick: handleDecrement
                }, "-"), React.createElement("button", {
                  style: buttonStyles,
                  onClick: handleReset
                }, "Reset"));
}

var make = ButtonsSection;

export {
  buttonStyles ,
  make ,
  
}
/* react Not a pure module */
