// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

var buttonStyles = {
  backgroundColor: "white",
  cursor: "pointer",
  marginTop: "10px",
  padding: "10px",
  borderRadius: "4px 4px 4px 4px"
};

function Button(Props) {
  var name = Props.name;
  return React.createElement("button", {
              style: buttonStyles
            }, "Hello " + name);
}

var make = Button;

export {
  buttonStyles ,
  make ,
  
}
/* react Not a pure module */
